set(GRAPHVIZ_GRAPH_NAME "Anasa")

set(GRAPHVIZ_EXECUTABLES TRUE)
set(GRAPHVIZ_STATIC_LIBS TRUE)
set(GRAPHVIZ_SHARED_LIBS TRUE)
set(GRAPHVIZ_MODULE_LIBS TRUE)
set(GRAPHVIZ_INTERFACE_LIBS TRUE)
set(GRAPHVIZ_OBJECT_LIBS TRUE)

# Important:
# Don't show random system/external libraries in the architecture diagram.
set(GRAPHVIZ_EXTERNAL_LIBS FALSE)

set(GRAPHVIZ_CUSTOM_TARGETS FALSE)

# Only generate the complete project graph.
set(GRAPHVIZ_GENERATE_PER_TARGET FALSE)
set(GRAPHVIZ_GENERATE_DEPENDERS FALSE)